apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ .Values.nodeapp.name }}
  labels:
    app: {{ .Values.nodeapp.name }}
    chart: {{ .Values.nodeapp.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- with .Values.nodeenvs }}
  DEVOPS_TEST_BACKEND_RELEASE_VERSION: {{ .devops_test_backend_release_version | b64enc }}
  DEVOPS_TEST_BACKEND_NAME: {{ .devops_test_backend_name | b64enc }}
  DEVOPS_TEST_ENV: {{ .devops_test_env | b64enc }}
  DEVOPS_TEST_PORT: {{ .devops_test_port | b64enc }}
  DEVOPS_TEST_DATABASE_NAME: {{ .devops_test_database_name | b64enc }}
  DEVOPS_TEST_DATABASE_USERNAME: {{ .devops_test_database_username | b64enc }}
  DEVOPS_TEST_DATABASE_PASSWORD: {{ .devops_test_database_password | b64enc }}
  DEVOPS_TEST_DATABASE_HOST: {{ .devops_test_database_host | b64enc }}

  DEVOPS_TEST_DATABASE_PORT: {{ .devops_test_database_port | b64enc }}
  DEVOPS_TEST_DATABASE_POOL_SIZE_MAX: {{ .devops_test_database_pool_size_max | b64enc }}
  DEVOPS_TEST_DATABASE_POOL_SIZE_MIN: {{ .devops_test_database_pool_size_min | b64enc }}
  DEVOPS_TEST_DATABASE_TIMEOUT: {{ .devops_test_database_timeout | b64enc }}
  DEVOPS_TEST_DATABASE_POOL_SIZE_MIN: {{ .devops_test_database_pool_size_min | b64enc }}
  DEVOPS_TEST_BACKEND_AWS_USER_BUCKET_NAME: {{ .devops_test_backend_aws_user_bucket_name | b64enc }}
  DEVOPS_TEST_BACKEND_AWS_ACCESS_KEY: {{ .devops_test_backend_aws_access_key | b64enc }}
  DEVOPS_TEST_BACKEND_AWS_SECRET_KEY: {{ .devops_test_backend_aws_secret_key | b64enc }}
  DEVOPS_TEST_BACKEND_AWS_PREFIX: {{ .devops_test_backend_aws_prefix | b64enc }}
  DEVOPS_TEST_BACKEND_AWS_REGION: {{ .devops_test_backend_aws_region | b64enc }}
{{- end }}
