apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
    chart: {{ .Values.postgres.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- with .Values.postgresenv }}
  POSTGRES_USER: {{ .postgres_user | b64enc }}
  POSTGRES_DB: {{ .postgres_db | b64enc }}
  POSTGRES_PASSWORD: {{ .postgres_password | b64enc }}
{{- end }}
